import Head from 'next/head';
import { IntroSection } from '../components/IntroSection';
import {
  Box,
  Button,
  ButtonGroup,
  Flex,
  Skeleton,
  useColorModeValue,
  useDisclosure,
} from '@chakra-ui/react';
import useBalance from '../api/api';
import { WalletInfo } from '../components/WalletInfo';

export default function Home() {
  const { data, isLoading, isError } = useBalance();
  const isLoaded = !isLoading && !isError;
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <Box height={'94vh'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalletInfo walletData={data} isOpen={isOpen} onClose={onClose} />
      <ButtonGroup
        isAttached
        position={'absolute'}
        right={5}
        top={5}
        onClick={onOpen}
      >
        <Button colorScheme={'blue'}>
          <Flex>
            <Skeleton isLoaded={isLoaded}>
              {Number(data?.cardano?.adaAmount)?.toFixed(3)}
            </Skeleton>
            <Box ml={2}>ADA</Box>
          </Flex>
        </Button>
        <Button colorScheme={'blue'} variant={'outline'}>
          <Flex>
            <Skeleton isLoaded={isLoaded}>
              {Number(data?.arweave?.arweaveBalance)?.toFixed(3)}
            </Skeleton>
            <Box ml={2}>ARW</Box>
          </Flex>
        </Button>
      </ButtonGroup>
      <Box bg={useColorModeValue('gray.50', 'inherit')} height={'100%'}>
        <Box height={'100%'}>
          <IntroSection />
        </Box>
      </Box>
    </Box>
  );
}
