import Head from 'next/head';
import { IntroSection } from '../components/IntroSection';
import { Box, Button, ButtonGroup, useColorModeValue } from '@chakra-ui/react';

export default function Home() {
  return (
    <Box height={'94vh'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ButtonGroup isAttached position={'absolute'} right={5} top={5}>
        <Button colorScheme={'twitter'}>2.4321 ADA</Button>
        <Button colorScheme={'blue'} variant={'outline'}>
          0.2312 ARW
        </Button>
      </ButtonGroup>
      <Box bg={useColorModeValue('gray.50', 'inherit')} height={'100%'}>
        <Box height={'100%'}>
          <IntroSection />
        </Box>
      </Box>
    </Box>
  );
}
