import Head from 'next/head'
import {IntroSection} from "../components/IntroSection";
import {Box, Grid, useColorModeValue} from "@chakra-ui/react";
import {Footer} from "../components/Footer";


export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Box
                bg={useColorModeValue('gray.50', 'inherit')}
                height={"100vh"}
            >


                <Box height={"94%"}>
                    <IntroSection/>
                </Box>

                <Box height={"6%"}>
                    <Footer/>
                </Box>


            </Box>


        </div>
    )
}
